import { createContext, useContext, useEffect, useState } from 'react'

const LanguageContext = createContext()

const translations = {
  ar: {
    // Navbar
    nav_home: 'الرئيسية',
    nav_contact: 'تواصل معنا',
    nav_dashboard: 'لوحة التحكم',
    nav_map: 'الخريطة',
    nav_requests: 'الطلبات',
    nav_messages: 'الرسائل',
    nav_statistics: 'الإحصائيات',
    nav_admin: 'الإدارة',
    nav_notifications: 'الإشعارات',
    nav_profile: 'الملف الشخصي',
    nav_logout: 'خروج',
    nav_login: 'تسجيل الدخول',
    nav_register: 'إنشاء حساب',
    // Home Hero
    home_badge: 'مبادرة سيدي بلعباس الخضراء',
    home_hero_title1: 'نحو مدينة أنظف،',
    home_hero_title2: 'زجاجة بزجاجة',
    home_hero_desc: 'منصة GREEN GLASS تجمع بين المواطنين والمقاهي والمصانع لإعادة تدوير الزجاج في سيدي بلعباس. ساهم في حماية البيئة واحصل على مكافآت.',
    home_start_now: 'ابدأ الآن',
    home_login: 'تسجيل الدخول',
    home_learn_more: 'تعرف على المزيد',
    // Home Features
    home_features_title: 'كيف تعمل منصة GREEN GLASS',
    home_features_subtitle: 'نظام متكامل يسهل عملية جمع وإعادة تدوير الزجاج بخطوات بسيطة وفعالة.',
    feat_map_title: 'خريطة تفاعلية',
    feat_map_desc: 'اكتشف أقرب نقاط جمع الزجاج وحاويات إعادة التدوير في مدينتك بسهولة.',
    feat_collect_title: 'طلب الجمع',
    feat_collect_desc: 'قدم طلبات لجمع الزجاج من موقعك مباشرة، وسيقوم فريقنا بالمهمة.',
    feat_reward_title: 'نظام المكافآت',
    feat_reward_desc: 'اكسب نقاطاً مقابل كل كيلوغرام تعيد تدويره واستبدلها بمكافآت قيمة.',
    feat_stats_title: 'إحصائيات بيئية',
    feat_stats_desc: 'تابع أثرك الإيجابي على البيئة بالأرقام والإحصائيات المحدثة باستمرار.',
    // Home Audience
    home_audience_title1: 'منصة واحدة تجمع',
    home_audience_title2: 'كل الفاعلين',
    home_audience_title3: 'في المجتمع',
    home_audience_desc: 'سواء كنت فرداً يهتم ببيئته، أو صاحب عمل ينتج نفايات زجاجية، GREEN GLASS هي المنصة المثالية لك.',
    aud_individuals: 'الأفراد',
    aud_individuals_sub: 'مواطنون يجمعون الزجاج',
    aud_hotels: 'الفنادق والمقاهي',
    aud_hotels_sub: 'منتجو الزجاج بكميات',
    aud_collectors: 'جامعو الزجاج',
    aud_collectors_sub: 'شبكة النقل والجمع',
    aud_factories: 'المصانع',
    aud_factories_sub: 'شركاء إعادة التدوير',
    // Home Stats
    home_stats_title: 'أهدافنا البيئية',
    home_stats_subtitle: 'نطمح إلى صنع فارق حقيقي في سيدي بلعباس والمساهمة في بناء مستقبل مستدام.',
    stats_goal: 'هدفنا',
    stats_tons: 'طن من الزجاج المُعاد تدويره',
    stats_users: 'مستخدم نشط',
    stats_cafes: 'مقهى ومطعم شريك',
    stats_points: 'نقطة مكافآت موزعة',
    // Home CTA
    home_cta_title: 'كن جزءاً من الحل، ابدأ إعادة التدوير اليوم',
    home_cta_desc: 'انضم إلى مجتمع GREEN GLASS وحول نفايات الزجاج إلى قيمة بيئية واقتصادية.',
    home_cta_btn: 'ابدأ الآن',
    // Contact
    contact_title: 'تواصل معنا',
    contact_subtitle: 'متاحون للمشاريع والشراكات في سيدي بلعباس والجزائر — نسعد بسماعك.',
    contact_brand_desc: 'منصة إعادة تدوير الزجاج — سيدي بلعباس، الجزائر',
    contact_email_label: 'البريد الإلكتروني',
    contact_phone_label: 'الهاتف / واتساب',
    contact_location_label: 'الموقع',
    contact_social: 'تابعونا على وسائل التواصل الاجتماعي',
    contact_form_title: 'أرسل رسالة',
    contact_name: 'الاسم',
    contact_name_ph: 'اسمك الكامل',
    contact_email: 'البريد الإلكتروني',
    contact_message: 'الرسالة',
    contact_message_ph: 'اكتب رسالتك هنا...',
    contact_send_btn: 'لنعمل معاً',
    contact_sent_title: 'تم إرسال رسالتك!',
    contact_sent_desc: 'شكراً لتواصلك معنا، سنرد عليك في أقرب وقت ممكن.',
    // Footer
    footer_rights: 'جميع الحقوق محفوظة.',
    // Login
    login_title: 'تسجيل الدخول',
    login_subtitle: 'أدخل بياناتك للوصول إلى حسابك',
    login_email: 'البريد الإلكتروني',
    login_password: 'كلمة المرور',
    login_btn: 'تسجيل الدخول',
    login_no_account: 'ليس لديك حساب؟',
    login_register_link: 'إنشاء حساب جديد',
    // Register
    register_title: 'إنشاء حساب جديد',
    register_subtitle: 'انضم إلى مجتمع GREEN GLASS',
    register_name: 'الاسم الكامل',
    register_email: 'البريد الإلكتروني',
    register_phone: 'رقم الهاتف',
    register_password: 'كلمة المرور',
    register_role: 'نوع الحساب',
    register_role_user: 'مستخدم (أفراد / مؤسسات)',
    register_role_collector: 'جامع زجاج',
    register_btn: 'إنشاء الحساب',
    register_have_account: 'لديك حساب بالفعل؟',
    register_login_link: 'تسجيل الدخول',
    // CreateRequest
    create_title: 'إنشاء طلب جمع جديد',
    create_subtitle: 'املأ النموذج أدناه لطلب جمع الزجاج',
    create_entity_name: 'اسم الكيان / الموقع',
    create_entity_type: 'نوع الكيان',
    create_address: 'العنوان الكامل',
    create_location: 'الموقع على الخريطة',
    create_detect_location: 'تحديد الموقع الحالي',
    create_location_set: 'تم تحديد الموقع',
    create_quantity: 'كمية الزجاج (كيلوغرام)',
    create_glass_type: 'نوع الزجاج',
    create_description: 'وصف إضافي',
    create_submit: 'إنشاء الطلب',
    create_loading: 'جاري الإنشاء...',
    // Notifications
    notif_title: 'الإشعارات',
    notif_mark_all: 'تعليم الكل كمقروء',
    notif_empty: 'لا توجد إشعارات',
    notif_now: 'الآن',
    // Dashboard
    dash_welcome: 'مرحباً،',
    dash_points: 'نقاطك',
    dash_requests: 'طلباتك',
    dash_collected: 'تم جمعه',
    dash_kg: 'كغ',
    // Common
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    save: 'حفظ',
    cancel: 'إلغاء',
    submit: 'إرسال',
    back: 'رجوع',
    search: 'بحث',
    filter: 'تصفية',
    all: 'الكل',
    status_pending: 'قيد الانتظار',
    status_accepted: 'مقبول',
    status_completed: 'مكتمل',
    status_cancelled: 'ملغي',
  },
  en: {
    // Navbar
    nav_home: 'Home',
    nav_contact: 'Contact Us',
    nav_dashboard: 'Dashboard',
    nav_map: 'Map',
    nav_requests: 'Requests',
    nav_messages: 'Messages',
    nav_statistics: 'Statistics',
    nav_admin: 'Admin',
    nav_notifications: 'Notifications',
    nav_profile: 'Profile',
    nav_logout: 'Logout',
    nav_login: 'Login',
    nav_register: 'Sign Up',
    // Home Hero
    home_badge: 'Sidi Bel Abbes Green Initiative',
    home_hero_title1: 'Towards a Cleaner City,',
    home_hero_title2: 'Bottle by Bottle',
    home_hero_desc: 'GREEN GLASS connects citizens, cafes, and factories for glass recycling in Sidi Bel Abbes. Protect the environment and earn rewards.',
    home_start_now: 'Get Started',
    home_login: 'Login',
    home_learn_more: 'Learn More',
    // Home Features
    home_features_title: 'How GREEN GLASS Works',
    home_features_subtitle: 'A complete system that makes glass collection and recycling simple and effective.',
    feat_map_title: 'Interactive Map',
    feat_map_desc: 'Discover the nearest glass collection points and recycling bins in your city with ease.',
    feat_collect_title: 'Collection Request',
    feat_collect_desc: 'Submit glass collection requests from your location directly — our team will handle the rest.',
    feat_reward_title: 'Rewards System',
    feat_reward_desc: 'Earn points for every kilogram you recycle and redeem them for valuable rewards.',
    feat_stats_title: 'Environmental Stats',
    feat_stats_desc: 'Track your positive environmental impact with continuously updated numbers and statistics.',
    // Home Audience
    home_audience_title1: 'One Platform Connecting',
    home_audience_title2: 'All Stakeholders',
    home_audience_title3: 'in the Community',
    home_audience_desc: 'Whether you are an individual who cares about the environment, or a business that produces glass waste, GREEN GLASS is the right platform for you.',
    aud_individuals: 'Individuals',
    aud_individuals_sub: 'Citizens who collect glass',
    aud_hotels: 'Hotels & Cafes',
    aud_hotels_sub: 'High-volume glass producers',
    aud_collectors: 'Collectors',
    aud_collectors_sub: 'Transport & collection network',
    aud_factories: 'Factories',
    aud_factories_sub: 'Recycling partners',
    // Home Stats
    home_stats_title: 'Our Environmental Goals',
    home_stats_subtitle: 'We aim to make a real difference in Sidi Bel Abbes and contribute to a sustainable future.',
    stats_goal: 'Our Goal',
    stats_tons: 'tons of recycled glass',
    stats_users: 'active users',
    stats_cafes: 'partner cafes & restaurants',
    stats_points: 'reward points distributed',
    // Home CTA
    home_cta_title: 'Be Part of the Solution — Start Recycling Today',
    home_cta_desc: 'Join the GREEN GLASS community and turn glass waste into environmental and economic value.',
    home_cta_btn: 'Get Started',
    // Contact
    contact_title: 'Contact Us',
    contact_subtitle: 'Available for projects and partnerships in Sidi Bel Abbes and Algeria — we\'d love to hear from you.',
    contact_brand_desc: 'Glass Recycling Platform — Sidi Bel Abbes, Algeria',
    contact_email_label: 'Email',
    contact_phone_label: 'Phone / WhatsApp',
    contact_location_label: 'Location',
    contact_social: 'Follow us on social media',
    contact_form_title: 'Send a Message',
    contact_name: 'Name',
    contact_name_ph: 'Your full name',
    contact_email: 'Email',
    contact_message: 'Message',
    contact_message_ph: 'Write your message here...',
    contact_send_btn: "Let's Work Together",
    contact_sent_title: 'Message Sent!',
    contact_sent_desc: 'Thank you for reaching out. We will get back to you as soon as possible.',
    // Footer
    footer_rights: 'All rights reserved.',
    // Login
    login_title: 'Login',
    login_subtitle: 'Enter your credentials to access your account',
    login_email: 'Email',
    login_password: 'Password',
    login_btn: 'Login',
    login_no_account: "Don't have an account?",
    login_register_link: 'Create a new account',
    // Register
    register_title: 'Create a New Account',
    register_subtitle: 'Join the GREEN GLASS community',
    register_name: 'Full Name',
    register_email: 'Email',
    register_phone: 'Phone Number',
    register_password: 'Password',
    register_role: 'Account Type',
    register_role_user: 'User (Individuals / Businesses)',
    register_role_collector: 'Glass Collector',
    register_btn: 'Create Account',
    register_have_account: 'Already have an account?',
    register_login_link: 'Login',
    // CreateRequest
    create_title: 'Create New Collection Request',
    create_subtitle: 'Fill in the form below to request glass collection',
    create_entity_name: 'Entity / Location Name',
    create_entity_type: 'Entity Type',
    create_address: 'Full Address',
    create_location: 'Map Location',
    create_detect_location: 'Detect Current Location',
    create_location_set: 'Location set',
    create_quantity: 'Glass Quantity (kg)',
    create_glass_type: 'Glass Type',
    create_description: 'Additional Description',
    create_submit: 'Create Request',
    create_loading: 'Creating...',
    // Notifications
    notif_title: 'Notifications',
    notif_mark_all: 'Mark all as read',
    notif_empty: 'No notifications',
    notif_now: 'Now',
    // Dashboard
    dash_welcome: 'Welcome,',
    dash_points: 'Your Points',
    dash_requests: 'Your Requests',
    dash_collected: 'Collected',
    dash_kg: 'kg',
    // Common
    loading: 'Loading...',
    error: 'An error occurred',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    back: 'Back',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    status_pending: 'Pending',
    status_accepted: 'Accepted',
    status_completed: 'Completed',
    status_cancelled: 'Cancelled',
  }
}

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem('gg_lang') || 'ar')

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = lang
    localStorage.setItem('gg_lang', lang)
  }, [lang])

  const setLang = (l) => setLangState(l)
  const toggleLang = () => setLangState(prev => prev === 'ar' ? 'en' : 'ar')
  const t = (key) => translations[lang]?.[key] ?? translations['ar'][key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, t, setLang, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
